##### In this notebook, we are going to cover some of the most fundamentals concepts of tensors using Tensorflow

More specifically, we are going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulation tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with Tensorflow (or TPUs)
* Exercises to try yourself!

<b>Introduction to tensors

In [5]:
## Import Tensorflow
import tensorflow as tf

tf.__version__

'2.11.0'

<b>Create tensors with `tf.constant()`

In [7]:
## Create tensors with tf.constant()
scaler = tf.constant(3)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [8]:
## Check the number of  dimensions of a tensor (ndim stands for number of dimensions)
scaler.ndim

0

In [9]:
## Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [11]:
## Check the dimension of our vectır
vector.ndim

1

In [12]:
## Create a matrix
matrix = tf.constant([[1,1], 
                      [2,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2]])>

In [14]:
## Check the dimension of our matrix
matrix.ndim

2

In [16]:
## Create another matrix
another_matrix = tf.constant([[1., 1.],
                              [2., 2.],
                              [3., 3.]], dtype=tf.float16) ## Specify the data type with dtype

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 1.],
       [2., 2.],
       [3., 3.]], dtype=float16)>

In [18]:
## Check the ndim of our another_matrix
another_matrix.ndim

2

In [25]:
## Create tensor
    # Number of outer list => 2
    # Number of row => 3
    # Number of columns => 4
tensor = tf.constant([[[1, 1, 1, 1],
                       [2, 2, 2, 2], 
                       [3, 3, 3, 3]],

                      [[4, 4, 4, 4], 
                       [5, 5, 5, 5], 
                       [6, 6, 6, 6]]])

tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]]])>

In [27]:
## Check the ndim of our tensor
tensor.ndim

3

<b>Create tensors with `tf.Variable()`

In [34]:
## Create tensors with tf.Variable()
changeable_tensor = tf.Variable([1, 2])
unchangeable_tensor = tf.constant([1, 2])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>)

In [37]:
## Let's try change one of the variable in our changeable tensor
changeable_tensor[0] = 0

TypeError: 'ResourceVariable' object does not support item assignment

In [40]:
## How about we try .assign()
changeable_tensor[0].assign(0)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([0, 2])>

In [42]:
## Let's try change our unchangeable tensor
unchangeable_tensor[0] = 0

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [43]:
## How about we try with .assign() to change our unchangeable tensor
unchangeable_tensor[0].assign(0)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

<b>Creating radom tensors

In [62]:
## Random tensors are tensors of some abitrary size which contain random numbers.

## Create two random (but the same) tensors
random_tensor_1 = tf.random.Generator.from_seed(55)
random_tensor_1 = random_tensor_1.uniform(shape=(2, 3, 4))

random_tensor_2 = tf.random.Generator.from_seed(55)
random_tensor_2 = random_tensor_2.uniform(shape=(2, 3, 4))

## Are they equal?

random_tensor_1, random_tensor_2, random_tensor_1 == random_tensor_2

(<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[0.02760839, 0.99757504, 0.52172756, 0.20307171],
         [0.7182547 , 0.84263575, 0.9542595 , 0.90112185],
         [0.62839293, 0.08619452, 0.5679928 , 0.28763676]],
 
        [[0.18828917, 0.6658715 , 0.6190208 , 0.04422736],
         [0.49626625, 0.6474861 , 0.3557682 , 0.32033885],
         [0.33705008, 0.7391062 , 0.16512096, 0.41555858]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[0.02760839, 0.99757504, 0.52172756, 0.20307171],
         [0.7182547 , 0.84263575, 0.9542595 , 0.90112185],
         [0.62839293, 0.08619452, 0.5679928 , 0.28763676]],
 
        [[0.18828917, 0.6658715 , 0.6190208 , 0.04422736],
         [0.49626625, 0.6474861 , 0.3557682 , 0.32033885],
         [0.33705008, 0.7391062 , 0.16512096, 0.41555858]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=bool, numpy=
 array([[[ True,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True, 

<b>Shuffle the order of elements in a tensor

In [93]:
## Shuffle a tensor (usefull for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])

## Shuffle our non-shuffle data
tf.random.set_seed(55) ## Global level seed
shuffled = tf.random.shuffle(not_shuffled, seed=55) ## Operation level seed
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]])>

If we want our shuffled tensor to be same order, we have got to use global level random seed as well as operation level random seed:</br>
> Rule 4: "If both the global and operation seed are set: Both seeds are used in conjunction to determine the random sequence"

In [ ]:
## Reproducable Shuffle
tf.random.set_seed(55) ## Global level seed
shuffled = tf.random.shuffle(not_shuffled, seed=55) ## Operation level seed
shuffled

<b>Other ways to create tensors

In [95]:
## Create tensor of all ones
tf.ones([2, 3, 4])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [98]:
## Create tensor of all zeros
tf.zeros([2, 3, 4])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [99]:
# X = tf.constant(some_marix) # Capital for matrix or tensor
# y = tf.constant(vector) # non-Capital for vector

In [112]:
## We can also turn Numpy into tensor
import numpy as np

numpy_Array = np.arange(1, 25, dtype=np.int32)

numpy_To_Tensor = tf.constant(numpy_Array, shape=(2, 3, 4), dtype=tf.float16)
numpy_To_Tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]], dtype=float16)>

<b>Getting Information from tensors

In [124]:
## Shape: The length (number of element) of each of the dimension of a tensor
print(numpy_To_Tensor.shape)
## Rank: The number of dimension 
print(numpy_To_Tensor.ndim)
## Axis or dimension: A particular (spesifik, özel) dimension of a tensor
print(numpy_To_Tensor[0], numpy_To_Tensor[1]) ## (2, 3, 4)
## Size: Total number of items in the tensor
print(tf.size(numpy_To_Tensor))

(2, 3, 4)
3
tf.Tensor(
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]], shape=(3, 4), dtype=float16) tf.Tensor(
[[13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]], shape=(3, 4), dtype=float16)
tf.Tensor(24, shape=(), dtype=int32)


In [142]:
random_tensor = tf.random.Generator.from_seed(seed=55)
random_tensor = random_tensor.normal(shape=(2, 5, 2, 3))

## Two tensor with 5 matrix those matrix have (2, 3) matrix
print('Shape: ', random_tensor.shape)
print('Ndim (Number of Dimension): ', random_tensor.ndim)
print('Size: ', tf.size(random_tensor)) ## 2 * 5 * 2 * 3 = 60

Shape:  (2, 5, 2, 3)
Ndim (Number of Dimension):  4
Size:  tf.Tensor(60, shape=(), dtype=int32)


In [143]:
random_tensor

<tf.Tensor: shape=(2, 5, 2, 3), dtype=float32, numpy=
array([[[[-0.04082382,  2.6791053 ,  1.0914806 ],
         [ 0.33149615, -0.67958915,  0.44723678]],

        [[-0.17811584,  0.24882518,  0.49689844],
         [ 0.8259971 ,  1.0340209 , -0.24918637]],

        [[-1.5780283 , -0.92161775,  0.268676  ],
         [ 0.9418312 , -0.9465717 , -0.7108357 ]],

        [[ 1.2995545 , -0.6149066 , -1.4713507 ],
         [-0.10086866,  0.9603877 , -1.6370124 ]],

        [[ 0.17664973, -0.67038715, -0.503455  ],
         [-1.203792  , -2.5255601 ,  0.05080947]]],


       [[[ 1.7212061 , -0.6575125 ,  0.7939443 ],
         [ 1.3212339 ,  0.34584793, -0.6699328 ]],

        [[ 0.4604257 ,  0.514933  , -0.06519881],
         [-1.442522  , -0.48492542, -1.8364043 ]],

        [[ 0.91463274,  0.5145402 ,  0.5517507 ],
         [-0.3741098 , -0.28709963,  1.5089895 ]],

        [[-0.14833727, -1.2846565 ,  0.5484313 ],
         [ 0.10596129,  0.21793836,  0.7063839 ]],

        [[-0.19219153,  1.

<b> Indexing tensors </b></br>
Tensors can be indexed just like a Python list

In [195]:
## Get the first two elements of each dimension

vector = np.arange(0, 120)
Tensor = tf.constant(vector, shape=(4, 5, 2, 3))
Tensor

<tf.Tensor: shape=(4, 5, 2, 3), dtype=int32, numpy=
array([[[[  0,   1,   2],
         [  3,   4,   5]],

        [[  6,   7,   8],
         [  9,  10,  11]],

        [[ 12,  13,  14],
         [ 15,  16,  17]],

        [[ 18,  19,  20],
         [ 21,  22,  23]],

        [[ 24,  25,  26],
         [ 27,  28,  29]]],


       [[[ 30,  31,  32],
         [ 33,  34,  35]],

        [[ 36,  37,  38],
         [ 39,  40,  41]],

        [[ 42,  43,  44],
         [ 45,  46,  47]],

        [[ 48,  49,  50],
         [ 51,  52,  53]],

        [[ 54,  55,  56],
         [ 57,  58,  59]]],


       [[[ 60,  61,  62],
         [ 63,  64,  65]],

        [[ 66,  67,  68],
         [ 69,  70,  71]],

        [[ 72,  73,  74],
         [ 75,  76,  77]],

        [[ 78,  79,  80],
         [ 81,  82,  83]],

        [[ 84,  85,  86],
         [ 87,  88,  89]]],


       [[[ 90,  91,  92],
         [ 93,  94,  95]],

        [[ 96,  97,  98],
         [ 99, 100, 101]],

        [[102, 103, 104]

In [196]:
## First two tensors and first two matrix which are in those tensors
## First two rows and columns which are in those matrix which are in tensors
Tensor[0:2, 0:2 , 0:2 , 0:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 0,  1],
         [ 3,  4]],

        [[ 6,  7],
         [ 9, 10]]],


       [[[30, 31],
         [33, 34]],

        [[36, 37],
         [39, 40]]]])>

In [198]:
## Get the first element from each dimension from each index except for the final one
Tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 3), dtype=int32, numpy=array([[[[0, 1, 2]]]])>

In [233]:
## When we want to add an extra dimension, we can use those methods
## Those methods have same result

rank_2_tensor = tf.constant([[10, 7],
                    [3, 4]])

rank_3_tensor = tf.reshape(rank_2_tensor, shape=(2, 2, 1))

rank_3_tensor = rank_2_tensor[..., tf.newaxis]

rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]

rank_3_tensor = tf.expand_dims(rank_2_tensor, axis=-1)

<b>Matrix Multiplication (Dot Product)</b>
* In Machine learning, Matrix Multiplication is one of the most common tensor operations.

In [250]:
## If we want to multiply two matrix, First matrix's number of columns should be equal to second matrix's number of row
## When multiply two matrix, shape of result matrix would be first matrix's number of rows and second matrix's number of columns
tensor1 = tf.random.Generator.from_seed(seed=55)
tensor1 = tensor1.normal(shape=(2,2))

tensor2 = tf.random.Generator.from_seed(seed=55)
tensor2 = tensor2.uniform(shape=(2,2))

tf.linalg.matmul(tensor1, tensor2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.3966359, 0.5033257],
       [0.2030847, 1.1561513]], dtype=float32)>

In [253]:
## İf we have two matrix which have same shape, we can't multiply those matrix but if we transpose one matrix, we could be multiply
same_shape_tensor1 = tf.random.uniform([2, 3])
same_shape_tensor2 = tf.random.normal([2, 3])

transpose_same_shape_tensor2 = tf.transpose(same_shape_tensor2) ## Shape (3, 2)

tf.linalg.matmul(same_shape_tensor1, transpose_same_shape_tensor2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.5846004 ,  0.00575152],
       [-0.9271422 ,  0.24484438]], dtype=float32)>