##### In this notebook, we are going to cover some of the most fundamentals concepts of tensors using Tensorflow

More specifically, we are going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulation tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with Tensorflow (or TPUs)
* Exercises to try yourself!

Introduction to tensors

In [5]:
## Import Tensorflow
import tensorflow as tf

tf.__version__

'2.11.0'

Create tensors with `tf.constant()`

In [7]:
## Create tensors with tf.constant()
scaler = tf.constant(3)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [8]:
## Check the number of  dimensions of a tensor (ndim stands for number of dimensions)
scaler.ndim

0

In [9]:
## Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [11]:
## Check the dimension of our vectır
vector.ndim

1

In [12]:
## Create a matrix
matrix = tf.constant([[1,1], 
                      [2,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2]])>

In [14]:
## Check the dimension of our matrix
matrix.ndim

2

In [16]:
## Create another matrix
another_matrix = tf.constant([[1., 1.],
                              [2., 2.],
                              [3., 3.]], dtype=tf.float16) ## Specify the data type with dtype

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 1.],
       [2., 2.],
       [3., 3.]], dtype=float16)>

In [18]:
## Check the ndim of our another_matrix
another_matrix.ndim

2

In [25]:
## Create tensor
    # Number of outer list => 2
    # Number of row => 3
    # Number of columns => 4
tensor = tf.constant([[[1, 1, 1, 1],
                       [2, 2, 2, 2], 
                       [3, 3, 3, 3]],

                      [[4, 4, 4, 4], 
                       [5, 5, 5, 5], 
                       [6, 6, 6, 6]]])

tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]]])>

In [27]:
## Check the ndim of our tensor
tensor.ndim

3

Create tensors with `tf.Variable()`

In [34]:
## Create tensors with tf.Variable()
changeable_tensor = tf.Variable([1, 2])
unchangeable_tensor = tf.constant([1, 2])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>)

In [37]:
## Let's try change one of the variable in our changeable tensor
changeable_tensor[0] = 0

TypeError: 'ResourceVariable' object does not support item assignment

In [40]:
## How about we try .assign()
changeable_tensor[0].assign(0)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([0, 2])>

In [42]:
## Let's try change our unchangeable tensor
unchangeable_tensor[0] = 0

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [43]:
## How about we try with .assign() to change our unchangeable tensor
unchangeable_tensor[0].assign(0)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Creating radom tensors

In [62]:
## Random tensors are tensors of some abitrary size which contain random numbers.

## Create two random (but the same) tensors
random_tensor_1 = tf.random.Generator.from_seed(55)
random_tensor_1 = random_tensor_1.uniform(shape=(2, 3, 4))

random_tensor_2 = tf.random.Generator.from_seed(55)
random_tensor_2 = random_tensor_2.uniform(shape=(2, 3, 4))

## Are they equal?

random_tensor_1, random_tensor_2, random_tensor_1 == random_tensor_2

(<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[0.02760839, 0.99757504, 0.52172756, 0.20307171],
         [0.7182547 , 0.84263575, 0.9542595 , 0.90112185],
         [0.62839293, 0.08619452, 0.5679928 , 0.28763676]],
 
        [[0.18828917, 0.6658715 , 0.6190208 , 0.04422736],
         [0.49626625, 0.6474861 , 0.3557682 , 0.32033885],
         [0.33705008, 0.7391062 , 0.16512096, 0.41555858]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[0.02760839, 0.99757504, 0.52172756, 0.20307171],
         [0.7182547 , 0.84263575, 0.9542595 , 0.90112185],
         [0.62839293, 0.08619452, 0.5679928 , 0.28763676]],
 
        [[0.18828917, 0.6658715 , 0.6190208 , 0.04422736],
         [0.49626625, 0.6474861 , 0.3557682 , 0.32033885],
         [0.33705008, 0.7391062 , 0.16512096, 0.41555858]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=bool, numpy=
 array([[[ True,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True, 

Shuffle the order of elements in a tensor

In [93]:
## Shuffle a tensor (usefull for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])

## Shuffle our non-shuffle data
tf.random.set_seed(55) ## Global level seed
shuffled = tf.random.shuffle(not_shuffled, seed=55) ## Operation level seed
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]])>

Read through Tensorflow doc on random seed generation and explain beetween global level and operation level:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed